Repository criticalstack/e2d, pull requests merged in 2019-08, with the labels that each got.

#9 Add manager.Config option for etcd log level
  pkg/manager/config.go
  pkg/manager/manager.go
  pkg/manager/server.go
Labels: enhancement

#10 e2db: iterate indexes while deleting
  pkg/e2db/db_test.go
  pkg/e2db/key/key.go
  pkg/e2db/model.go
  pkg/e2db/query.go
  pkg/e2db/tx.go
  pkg/e2db/tx_test.go
Labels: e2db

#14 Use lower TTL for db lock session
  pkg/client/client.go
Labels: e2db, enhancement
